events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types; 
    default_type  application/octet-stream;

    sendfile        on;

    # Game Server (8888)
    server {
        listen 8888;
        server_name localhost;

        location / {
            # gameserver 컨테이너(8888 포트)로 트래픽 전달
            proxy_pass http://gameserver:8888;
            
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
        }
    }

    # Login Server (8885)
    server {
        listen 8885;
        server_name localhost;

        location / {
            # loginserver 컨테이너(8885 포트)로 트래픽 전달
            proxy_pass http://loginserver:8885;
            
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
        }
    }

    # Blazor (8880)
    server {
        listen 8880;
        server_name localhost;

        location / {
            # admintool 컨테이너(8880 포트)로 트래픽 전달
            proxy_pass http://admintool:8880;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}