// <auto-generated />
using System;
using Empen;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Empen.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    partial class MasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedData.Models.master_achievement", b =>
                {
                    b.Property<int>("achievement_id")
                        .HasColumnType("int");

                    b.Property<int>("achievement_category_id")
                        .HasColumnType("int");

                    b.Property<string>("achievement_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("achievement_param_1")
                        .HasColumnType("int");

                    b.Property<int>("achievement_param_2")
                        .HasColumnType("int");

                    b.Property<int>("achievement_param_3")
                        .HasColumnType("int");

                    b.Property<string>("achievement_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("achievement_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("reward_id_1")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_2")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_3")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("achievement_id");

                    b.ToTable("master_achievement");
                });

            modelBuilder.Entity("SharedData.Models.master_achievement_category", b =>
                {
                    b.Property<int>("achievement_category_id")
                        .HasColumnType("int");

                    b.Property<string>("category_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("flag")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("achievement_category_id");

                    b.ToTable("master_achievement_category");
                });

            modelBuilder.Entity("SharedData.Models.master_banner", b =>
                {
                    b.Property<int>("banner_id")
                        .HasColumnType("int");

                    b.Property<string>("banner_action_param")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("banner_action_type")
                        .HasColumnType("int");

                    b.Property<string>("banner_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("limited_param")
                        .HasColumnType("int");

                    b.Property<int>("limited_type")
                        .HasColumnType("int");

                    b.Property<int>("os_type")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<int>("show_place_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("banner_id");

                    b.ToTable("master_banner");
                });

            modelBuilder.Entity("SharedData.Models.master_character", b =>
                {
                    b.Property<int>("character_id")
                        .HasColumnType("int");

                    b.Property<string>("character_comment_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("character_comment_1_motion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("character_comment_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("character_comment_2_motion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("character_comment_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("character_comment_3_motion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("character_critical_damage")
                        .HasColumnType("int");

                    b.Property<int>("character_critical_rate")
                        .HasColumnType("int");

                    b.Property<string>("character_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("character_grade")
                        .HasColumnType("int");

                    b.Property<int>("character_grade_max")
                        .HasColumnType("int");

                    b.Property<int>("character_level_max")
                        .HasColumnType("int");

                    b.Property<string>("character_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("piece_amount_duplicate")
                        .HasColumnType("int");

                    b.Property<int>("piece_item_id")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("character_id");

                    b.ToTable("master_character");
                });

            modelBuilder.Entity("SharedData.Models.master_character_grade", b =>
                {
                    b.Property<int>("character_grade_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("character_grade_id"));

                    b.Property<int>("character_id")
                        .HasColumnType("int");

                    b.Property<int>("critical_damage")
                        .HasColumnType("int");

                    b.Property<int>("critical_rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("grade")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("price_token")
                        .HasColumnType("int");

                    b.Property<int>("require_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("character_grade_id");

                    b.HasIndex("character_id");

                    b.ToTable("master_character_grade");
                });

            modelBuilder.Entity("SharedData.Models.master_character_level", b =>
                {
                    b.Property<int>("character_level_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("character_level_id"));

                    b.Property<int>("atk")
                        .HasColumnType("int");

                    b.Property<int>("character_id")
                        .HasColumnType("int");

                    b.Property<int>("def")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("hp")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("item_1_amount")
                        .HasColumnType("int");

                    b.Property<int>("item_2_amount")
                        .HasColumnType("int");

                    b.Property<int>("item_3_amount")
                        .HasColumnType("int");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<int>("resource_item_id_1")
                        .HasColumnType("int");

                    b.Property<int>("resource_item_id_2")
                        .HasColumnType("int");

                    b.Property<int>("resource_item_id_3")
                        .HasColumnType("int");

                    b.Property<int>("stance")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("character_level_id");

                    b.HasIndex("character_id");

                    b.ToTable("master_character_level");
                });

            modelBuilder.Entity("SharedData.Models.master_daily_login_bonus", b =>
                {
                    b.Property<int>("daily_login_bonus_id")
                        .HasColumnType("int");

                    b.Property<string>("back_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("title_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("daily_login_bonus_id");

                    b.ToTable("master_daily_login_bonus");
                });

            modelBuilder.Entity("SharedData.Models.master_daily_login_bonus_day", b =>
                {
                    b.Property<int>("daily_login_bonus_day_id")
                        .HasColumnType("int");

                    b.Property<int>("daily_login_bonus_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("reward_id_1")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("total_login_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("daily_login_bonus_day_id");

                    b.HasIndex("daily_login_bonus_id");

                    b.ToTable("master_daily_login_bonus_day");
                });

            modelBuilder.Entity("SharedData.Models.master_gacha", b =>
                {
                    b.Property<int>("gacha_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("gacha_bonus_reward_group_lot_id")
                        .HasColumnType("int");

                    b.Property<int>("gacha_consume_value")
                        .HasColumnType("int");

                    b.Property<int>("gacha_coupon_item_id")
                        .HasColumnType("int");

                    b.Property<string>("gacha_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gacha_detail_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gacha_exec_10_id")
                        .HasColumnType("int");

                    b.Property<string>("gacha_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gacha_lot_group_id")
                        .HasColumnType("int");

                    b.Property<string>("gacha_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gacha_point")
                        .HasColumnType("int");

                    b.Property<int>("gacha_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("gacha_id");

                    b.HasIndex("gacha_exec_10_id");

                    b.HasIndex("gacha_lot_group_id");

                    b.ToTable("master_gacha");
                });

            modelBuilder.Entity("SharedData.Models.master_gacha_exec_10", b =>
                {
                    b.Property<int>("gacha_exec_10_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("gacha_bonus_reward_group_lot_id")
                        .HasColumnType("int");

                    b.Property<int>("gacha_consume_value")
                        .HasColumnType("int");

                    b.Property<int>("gacha_lot_count_1")
                        .HasColumnType("int");

                    b.Property<int>("gacha_lot_count_2")
                        .HasColumnType("int");

                    b.Property<int>("gacha_lot_count_3")
                        .HasColumnType("int");

                    b.Property<int>("gacha_lot_group_id_1")
                        .HasColumnType("int");

                    b.Property<int>("gacha_lot_group_id_2")
                        .HasColumnType("int");

                    b.Property<int>("gacha_lot_group_id_3")
                        .HasColumnType("int");

                    b.Property<int>("gacha_point")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("gacha_exec_10_id");

                    b.ToTable("master_gacha_exec_10");
                });

            modelBuilder.Entity("SharedData.Models.master_gacha_lot", b =>
                {
                    b.Property<int>("gacha_lot_id")
                        .HasColumnType("int");

                    b.Property<int>("character_level")
                        .HasColumnType("int");

                    b.Property<int>("character_plus_lot_group")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("gacha_character_id")
                        .HasColumnType("int");

                    b.Property<int>("gacha_lot_group_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("gacha_lot_id");

                    b.HasIndex("gacha_character_id");

                    b.HasIndex("gacha_lot_group_id");

                    b.ToTable("master_gacha_lot");
                });

            modelBuilder.Entity("SharedData.Models.master_gacha_lot_group", b =>
                {
                    b.Property<int>("gacha_lot_group_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("gacha_lot_group_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gacha_lot_group_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("gacha_lot_group_id");

                    b.ToTable("master_gacha_lot_group");
                });

            modelBuilder.Entity("SharedData.Models.master_item", b =>
                {
                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("expire_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("item_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_image_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("item_param_1")
                        .HasColumnType("int");

                    b.Property<int?>("item_param_2")
                        .HasColumnType("int");

                    b.Property<int>("item_type")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("tab_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("item_id");

                    b.ToTable("master_item");
                });

            modelBuilder.Entity("SharedData.Models.master_mail", b =>
                {
                    b.Property<int>("mail_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("important_flag")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("mail_body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail_subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sender_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("mail_id");

                    b.ToTable("master_mail");
                });

            modelBuilder.Entity("SharedData.Models.master_notice", b =>
                {
                    b.Property<int>("notice_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notice_id"));

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("notice_banner_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notice_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notice_link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notice_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("notice_type")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("notice_id");

                    b.ToTable("master_notice");
                });

            modelBuilder.Entity("SharedData.Models.master_product", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("prism")
                        .HasColumnType("int");

                    b.Property<string>("product_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("product_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("product_id");

                    b.ToTable("master_product");
                });

            modelBuilder.Entity("SharedData.Models.master_product_set", b =>
                {
                    b.Property<int>("product_set_id")
                        .HasColumnType("int");

                    b.Property<int>("buy_upper_limit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("reward_id_1")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_2")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_3")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("product_set_id");

                    b.ToTable("master_product_set");
                });

            modelBuilder.Entity("SharedData.Models.master_product_set_piece", b =>
                {
                    b.Property<int>("product_set_piece_id")
                        .HasColumnType("int");

                    b.Property<int>("buy_upper_limit")
                        .HasColumnType("int");

                    b.Property<int>("cost_item_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("price_piece")
                        .HasColumnType("int");

                    b.Property<string>("product_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reward_id_1")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_2")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_3")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("product_set_piece_id");

                    b.ToTable("master_product_set_piece");
                });

            modelBuilder.Entity("SharedData.Models.master_product_set_prism", b =>
                {
                    b.Property<int>("product_set_prism_id")
                        .HasColumnType("int");

                    b.Property<int>("buy_upper_limit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("price_prism")
                        .HasColumnType("int");

                    b.Property<string>("product_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reward_id_1")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_2")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_3")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("product_set_prism_id");

                    b.ToTable("master_product_set_prism");
                });

            modelBuilder.Entity("SharedData.Models.master_product_set_token", b =>
                {
                    b.Property<int>("product_set_token_id")
                        .HasColumnType("int");

                    b.Property<int>("buy_upper_limit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("is_package")
                        .HasColumnType("int");

                    b.Property<int>("package_display_reward_id")
                        .HasColumnType("int");

                    b.Property<int>("price_token")
                        .HasColumnType("int");

                    b.Property<string>("product_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reward_id_1")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_2")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_3")
                        .HasColumnType("int");

                    b.Property<int>("show_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("token_reward_group")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("product_set_token_id");

                    b.ToTable("master_product_set_token");
                });

            modelBuilder.Entity("SharedData.Models.master_reward", b =>
                {
                    b.Property<int>("reward_id")
                        .HasColumnType("int");

                    b.Property<string>("additional_param")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("object_amount")
                        .HasColumnType("int");

                    b.Property<int>("object_type")
                        .HasColumnType("int");

                    b.Property<int>("object_value")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("reward_id");

                    b.ToTable("master_reward");
                });

            modelBuilder.Entity("SharedData.Models.master_character_grade", b =>
                {
                    b.HasOne("SharedData.Models.master_character", "character")
                        .WithMany("character_grades")
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("character");
                });

            modelBuilder.Entity("SharedData.Models.master_character_level", b =>
                {
                    b.HasOne("SharedData.Models.master_character", "character")
                        .WithMany("character_levels")
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("character");
                });

            modelBuilder.Entity("SharedData.Models.master_daily_login_bonus_day", b =>
                {
                    b.HasOne("SharedData.Models.master_daily_login_bonus", "daily_login_bonus")
                        .WithMany("daily_login_bonus_days")
                        .HasForeignKey("daily_login_bonus_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("daily_login_bonus");
                });

            modelBuilder.Entity("SharedData.Models.master_gacha", b =>
                {
                    b.HasOne("SharedData.Models.master_gacha_exec_10", "gacha_exec_10")
                        .WithMany("gachas")
                        .HasForeignKey("gacha_exec_10_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SharedData.Models.master_gacha_lot_group", "gacha_lot_group")
                        .WithMany("gachas")
                        .HasForeignKey("gacha_lot_group_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("gacha_exec_10");

                    b.Navigation("gacha_lot_group");
                });

            modelBuilder.Entity("SharedData.Models.master_gacha_lot", b =>
                {
                    b.HasOne("SharedData.Models.master_character", "character")
                        .WithMany("gacha_lots")
                        .HasForeignKey("gacha_character_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SharedData.Models.master_gacha_lot_group", "gacha_lot_group")
                        .WithMany("gacha_lots")
                        .HasForeignKey("gacha_lot_group_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("character");

                    b.Navigation("gacha_lot_group");
                });

            modelBuilder.Entity("SharedData.Models.master_character", b =>
                {
                    b.Navigation("character_grades");

                    b.Navigation("character_levels");

                    b.Navigation("gacha_lots");
                });

            modelBuilder.Entity("SharedData.Models.master_daily_login_bonus", b =>
                {
                    b.Navigation("daily_login_bonus_days");
                });

            modelBuilder.Entity("SharedData.Models.master_gacha_exec_10", b =>
                {
                    b.Navigation("gachas");
                });

            modelBuilder.Entity("SharedData.Models.master_gacha_lot_group", b =>
                {
                    b.Navigation("gacha_lots");

                    b.Navigation("gachas");
                });
#pragma warning restore 612, 618
        }
    }
}
