// <auto-generated />
using System;
using Empen;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Empen.Migrations.PersonDb
{
    [DbContext(typeof(PersonDbContext))]
    [Migration("20260310143439_fixPersonStatus")]
    partial class fixPersonStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedData.Models.person_achievement", b =>
                {
                    b.Property<int>("person_achievement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_achievement_id"));

                    b.Property<int>("achievement_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_achievement_id");

                    b.HasIndex("person_id", "achievement_id")
                        .IsUnique();

                    b.ToTable("person_achievement");
                });

            modelBuilder.Entity("SharedData.Models.person_character", b =>
                {
                    b.Property<int>("person_character_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_character_id"));

                    b.Property<int>("character_id")
                        .HasColumnType("int");

                    b.Property<int>("character_level")
                        .HasColumnType("int");

                    b.Property<int>("friendship_exp")
                        .HasColumnType("int");

                    b.Property<int>("friendship_level")
                        .HasColumnType("int");

                    b.Property<int>("grade")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_character_id");

                    b.HasIndex("person_id", "character_id")
                        .IsUnique();

                    b.ToTable("person_character");
                });

            modelBuilder.Entity("SharedData.Models.person_gacha", b =>
                {
                    b.Property<int>("person_gacha_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_gacha_id"));

                    b.Property<int>("gacha_count")
                        .HasColumnType("int");

                    b.Property<int>("gacha_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_gacha_id");

                    b.HasIndex("person_id", "gacha_id");

                    b.ToTable("person_gacha");
                });

            modelBuilder.Entity("SharedData.Models.person_item", b =>
                {
                    b.Property<int>("person_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_item_id"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_item_id");

                    b.HasIndex("person_id", "item_id")
                        .IsUnique();

                    b.ToTable("person_item");
                });

            modelBuilder.Entity("SharedData.Models.person_item_history", b =>
                {
                    b.Property<int>("person_item_history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_item_history_id"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_item_history_id");

                    b.HasIndex("person_id", "insert_date");

                    b.ToTable("person_item_history");
                });

            modelBuilder.Entity("SharedData.Models.person_levelup", b =>
                {
                    b.Property<int>("person_levelup_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_levelup_id"));

                    b.Property<int>("character_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_levelup_id");

                    b.ToTable("person_levelup");
                });

            modelBuilder.Entity("SharedData.Models.person_limitbreak", b =>
                {
                    b.Property<int>("person_limitbreak_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_limitbreak_id"));

                    b.Property<int>("character_id")
                        .HasColumnType("int");

                    b.Property<int>("grade")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_limitbreak_id");

                    b.HasIndex("person_id", "character_id");

                    b.ToTable("person_limitbreak");
                });

            modelBuilder.Entity("SharedData.Models.person_login", b =>
                {
                    b.Property<int>("person_login_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_login_id"));

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_login_id");

                    b.HasIndex("person_id", "insert_date");

                    b.ToTable("person_login");
                });

            modelBuilder.Entity("SharedData.Models.person_loginbonus", b =>
                {
                    b.Property<int>("person_loginbonus_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_loginbonus_id"));

                    b.Property<int>("daily_login_bonus_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("pre_login_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("total_login_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_loginbonus_id");

                    b.HasIndex("person_id", "daily_login_bonus_id");

                    b.ToTable("person_loginbonus");
                });

            modelBuilder.Entity("SharedData.Models.person_mail", b =>
                {
                    b.Property<int>("person_mail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_mail_id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("expire_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_receive")
                        .HasColumnType("bit");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<int>("reward_id_1")
                        .HasColumnType("int");

                    b.Property<int>("reward_id_1_amount")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_2")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_2_amount")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_3")
                        .HasColumnType("int");

                    b.Property<int?>("reward_id_3_amount")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_mail_id");

                    b.HasIndex("person_id", "insert_date");

                    b.HasIndex("person_id", "is_receive");

                    b.ToTable("person_mail");
                });

            modelBuilder.Entity("SharedData.Models.person_product", b =>
                {
                    b.Property<int>("person_product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_product_id"));

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_product_id");

                    b.ToTable("person_product");
                });

            modelBuilder.Entity("SharedData.Models.person_product_set_piece", b =>
                {
                    b.Property<int>("person_product_set_piece_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_product_set_piece_id"));

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("product_set_piece_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_product_set_piece_id");

                    b.ToTable("person_product_set_piece");
                });

            modelBuilder.Entity("SharedData.Models.person_product_set_prism", b =>
                {
                    b.Property<int>("person_product_set_prism_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_product_set_prism_id"));

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("product_set_prism_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_product_set_prism_id");

                    b.ToTable("person_product_set_prism");
                });

            modelBuilder.Entity("SharedData.Models.person_product_set_token", b =>
                {
                    b.Property<int>("person_product_set_token_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_product_set_token_id"));

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("product_set_token_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_product_set_token_id");

                    b.ToTable("person_product_set_token");
                });

            modelBuilder.Entity("SharedData.Models.person_status", b =>
                {
                    b.Property<int>("person_status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_status_id"));

                    b.Property<int>("character_amount_max")
                        .HasColumnType("int");

                    b.Property<int>("character_storage_amount_max")
                        .HasColumnType("int");

                    b.Property<int>("display_person_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("exp")
                        .HasColumnType("int");

                    b.Property<int>("film")
                        .HasColumnType("int");

                    b.Property<int>("gift")
                        .HasColumnType("int");

                    b.Property<DateTime>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("introduce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("leader_person_character_id")
                        .HasColumnType("int");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<int>("manual")
                        .HasColumnType("int");

                    b.Property<string>("person_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.Property<string>("person_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prism")
                        .HasColumnType("int");

                    b.Property<int>("token")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("person_status_id");

                    b.HasIndex("display_person_id")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("person_id")
                        .IsUnique();

                    b.ToTable("person_status");
                });
#pragma warning restore 612, 618
        }
    }
}
